# Generated by Django 2.2.11 on 2021-05-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0003_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
